import os

MY_PHONE_NUMBER = os.environ.get("MY_PHONE_NUMBER")
TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER")
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN")
TEST_TWILIO_ACCOUNT_SID = os.environ.get("TEST_TWILIO_ACCOUNT_SID")
TEST_TWILIO_AUTH_TOKEN = os.environ.get("TEST_TWILIO_AUTH_TOKEN")
FIREBASE_URL = os.environ.get("FIREBASE_URL")
